module.exports = [
  {
    // emoji: '🎨',
    // code: ':art:',
    section: 'Improving structure / format of the code.',
    type: 'style',
  },
  {
    // emoji: '⚡️',
    // code: ':zap:',
    section: 'Improving performance.',
    type: 'perf',
  },
  {
    // emoji: '🔥',
    // code: ':fire:',
    section: 'Removing code or files.',
    type: 'prune',
  },
  {
    // emoji: '🐛',
    // code: ':bug:',
    section: 'Fixing a bug.',
    type: 'fix',
  },
  {
    // emoji: '🚑',
    // code: ':ambulance:',
    section: 'Critical hotfix.',
    type: 'quickfix',
  },
  {
    // emoji: '✨',
    // code: ':sparkles:',
    section: 'Introducing new features.',
    type: 'feature',
  },
  {
    // emoji: '📝',
    // code: ':pencil:',
    section: 'Writing docs.',
    type: 'docs',
  },
  {
    // emoji: '🚀',
    // code: ':rocket:',
    section: 'Deploying stuff.',
    type: 'deploy',
  },
  {
    // emoji: '💄',
    // code: ':lipstick:',
    section: 'Updating the UI and style files.',
    type: 'ui',
  },
  {
    // emoji: '🎉',
    // code: ':tada:',
    section: 'Initial commit.',
    type: 'init',
  },
  {
    // emoji: '✅',
    // code: ':white_check_mark:',
    section: 'Adding tests.',
    type: 'test',
  },
  {
    // emoji: '🔒',
    // code: ':lock:',
    section: 'Fixing security issues.',
    type: 'security',
  },
  {
    // emoji: '🍎',
    // code: ':apple:',
    section: 'Fixing something on macOS.',
    type: 'osx',
  },
  {
    // emoji: '🐧',
    // code: ':penguin:',
    section: 'Fixing something on Linux.',
    type: 'linux',
  },
  {
    // emoji: '🏁',
    // code: ':checkered_flag:',
    section: 'Fixing something on Windows.',
    type: 'windows',
  },
  {
    // emoji: '🤖',
    // code: ':robot:',
    section: 'Fixing something on Android.',
    type: 'android',
  },
  {
    // emoji: '🍏',
    // code: ':green_apple:',
    section: 'Fixing something on iOS.',
    type: 'ios',
  },
  {
    // emoji: '🔖',
    // code: ':bookmark:',
    section: 'Releasing / Version tags.',
    type: 'release',
  },
  {
    // emoji: '🚨',
    // code: ':rotating_light:',
    section: 'Removing linter warnings.',
    type: 'lint',
  },
  {
    // emoji: '🚧',
    // code: ':construction:',
    section: 'Work in progress.',
    type: 'wip',
  },
  {
    // emoji: '💚',
    // code: ':green_heart:',
    section: 'Fixing CI Build.',
    type: 'fix-ci',
  },
  {
    // emoji: '⬇️',
    // code: ':arrow_down:',
    section: ' Downgrading dependencies.',
    type: 'downgrade',
  },
  {
    // emoji: '⬆️',
    // code: ':arrow_up:',
    section: ' Upgrading dependencies.',
    type: 'upgrade',
  },
  {
    // emoji: '📌',
    // code: ':pushpin:',
    section: 'Pinning dependencies to specific versions.',
    type: 'pushpin',
  },
  {
    // emoji: '👷',
    // code: ':construction_worker:',
    section: 'Adding CI build system.',
    type: 'ci',
  },
  {
    // emoji: '📈',
    // code: ':chart_with_upwards_trend:',
    section: 'Adding analytics or tracking code.',
    type: 'analytics',
  },
  {
    // emoji: '♻️',
    // code: ':recycle:',
    section: ' Refactoring code.',
    type: 'refactoring',
  },
  {
    // emoji: '🐳',
    // code: ':whale:',
    section: 'Work about Docker.',
    type: 'docker',
  },
  {
    // emoji: '➕',
    // code: ':heavy_plus_sign:',
    section: 'Adding a dependency.',
    type: 'dep-add',
  },
  {
    // emoji: '➖',
    // code: ':heavy_minus_sign:',
    section: 'Removing a dependency.',
    type: 'dep-rm',
  },
  {
    // emoji: '🔧',
    // code: ':wrench:',
    section: 'Changing configuration files.',
    type: 'config',
  },
  {
    // emoji: '🌐',
    // code: ':globe_with_meridians:',
    section: 'Internationalization and localization.',
    type: 'i18n',
  },
  {
    // emoji: '✏️',
    // code: ':pencil2:',
    section: ' Fixing typos.',
    type: 'typo',
  },
  {
    // emoji: '💩',
    // code: ':poop:',
    section: 'Writing bad code that needs to be improved.',
    type: 'poo',
  },
  {
    // emoji: '⏪',
    // code: ':rewind:',
    section: 'Reverting changes.',
    type: 'revert',
  },
  {
    // emoji: '🔀',
    // code: ':twisted_rightwards_arrows:',
    section: 'Merging branches.',
    type: 'merge',
  },
  {
    // emoji: '📦',
    // code: ':package:',
    section: 'Updating compiled files or packages.',
    type: 'dep-up',
  },
  {
    // emoji: '👽',
    // code: ':alien:',
    section: 'Updating code due to external API changes.',
    type: 'compat',
  },
  {
    // emoji: '🚚',
    // code: ':truck:',
    section: 'Moving or renaming files.',
    type: 'mv',
  },
  {
    // emoji: '📄',
    // code: ':page_facing_up:',
    section: 'Adding or updating license.',
    type: 'license',
  },
  {
    // emoji: '💥',
    // code: ':boom:',
    section: 'Introducing breaking changes.',
    type: 'breaking',
  },
  {
    // emoji: '🍱',
    // code: ':bento:',
    section: 'Adding or updating assets.',
    type: 'assets',
  },
  {
    // emoji: '👌',
    // code: ':ok_hand:',
    section: 'Updating code due to code review changes.',
    type: 'review',
  },
  {
    // emoji: '♿️',
    // code: ':wheelchair:',
    section: 'Improving accessibility.',
    type: 'access',
  },
  {
    // emoji: '💡',
    // code: ':bulb:',
    section: 'Documenting source code.',
    type: 'docs-code',
  },
  {
    // emoji: '🍻',
    // code: ':beers:',
    section: 'Writing code drunkenly.',
    type: 'beer',
  },
  {
    // emoji: '💬',
    // code: ':speech_balloon:',
    section: 'Updating text and literals.',
    type: 'texts',
  },
  {
    // emoji: '🗃',
    // code: ':card_file_box:',
    section: ' Performing database related changes.',
    type: 'db',
  },
  {
    // emoji: '🔊',
    // code: ':loud_sound:',
    section: 'Adding logs.',
    type: 'log-add',
  },
  {
    // emoji: '🔇',
    // code: ':mute:',
    section: 'Removing logs.',
    type: 'log-rm',
  },
  {
    // emoji: '👥',
    // code: ':busts_in_silhouette:',
    section: 'Adding contributor(s).',
    type: 'contrib-add',
  },
  {
    // emoji: '🚸',
    // code: ':children_crossing:',
    section: 'Improving user experience / usability.',
    type: 'ux',
  },
  {
    // emoji: '🏗',
    // code: ':building_construction:',
    section: ' Making architectural changes.',
    type: 'arch',
  },
  {
    // emoji: '📱',
    // code: ':iphone:',
    section: 'Working on responsive design.',
    type: 'iphone',
  },
  {
    // emoji: '🤡',
    // code: ':clown_face:',
    section: 'Mocking things.',
    type: 'clown-face',
  },
  {
    // emoji: '🥚',
    // code: ':egg:',
    section: 'Adding an easter egg.',
    type: 'egg',
  },
  {
    // emoji: '🙈',
    // code: ':see_no_evil:',
    section: 'Adding or updating a .gitignore file',
    type: 'see-no-evil',
  },
  {
    // emoji: '📸',
    // code: ':camera_flash:',
    section: 'Adding or updating snapshots',
    type: 'camera-flash',
  },
  {
    // emoji: '⚗',
    // code: ':alembic:',
    section: ' Experimenting new things',
    type: 'experiment',
  },
  {
    // emoji: '🔍',
    // code: ':mag:',
    section: 'Improving SEO',
    type: 'seo',
  },
  {
    // emoji: '☸️',
    // code: ':wheel_of_dharma:',
    section: ' Work about Kubernetes',
    type: 'k8s',
  },
  {
    // emoji: '🏷️',
    // code: ':label:',
    section: ' Adding or updating types (Flow, TypeScript)',
    type: 'types',
  },
  {
    // emoji: '🌱',
    // code: ':seedling:',
    section: 'Adding or updating seed files',
    type: 'seed',
  },
  {
    // emoji: '🚩',
    // code: ':triangular_flag_on_post:',
    section: 'Adding, updating, or removing feature flags',
    type: 'flags',
  },
  {
    // emoji: '💫',
    // code: ':dizzy:',
    section: 'Adding or updating animations and transitions',
    type: 'animation',
  },
];
