const MAJOR = 'major';
const MINOR = 'minor';
const PATCH = 'patch';

module.exports = [
  { breaking: true, release: MAJOR },
  { revert: true, release: PATCH },
  {
    emoji: '🎨',
    type: 'style',
    code: ':art:',
    description: 'Improving structure / format of the code.',
    release: PATCH,
  },
  {
    emoji: '⚡️',
    type: 'perf',
    code: ':zap:',
    description: 'Improving performance.',
    release: PATCH,
  },
  {
    emoji: '🔥',
    type: 'prune',
    code: ':fire:',
    description: 'Removing code or files.',
    release: PATCH,
  },
  {
    emoji: '🐛',
    type: 'fix',
    code: ':bug:',
    description: 'Fixing a bug.',
    release: PATCH,
  },
  {
    emoji: '🚑',
    type: 'quickfix',
    code: ':ambulance:',
    description: 'Critical hotfix.',
    release: MINOR,
  },
  {
    emoji: '✨',
    type: 'feature',
    code: ':sparkles:',
    description: 'Introducing new features.',
    release: MINOR,
  },
  {
    emoji: '📝',
    type: 'docs',
    code: ':pencil:',
    description: 'Writing docs.',
    release: false,
  },
  {
    emoji: '🚀',
    type: 'deploy',
    code: ':rocket:',
    description: 'Deploying stuff.',
    release: PATCH,
  },
  {
    emoji: '💄',
    type: 'ui',
    code: ':lipstick:',
    description: 'Updating the UI and style files.',
    release: PATCH,
  },
  {
    emoji: '🎉',
    type: 'init',
    code: ':tada:',
    description: 'Initial commit.',
    release: PATCH,
  },
  {
    emoji: '✅',
    type: 'test',
    code: ':white_check_mark:',
    description: 'Adding tests.',
    release: false,
  },
  {
    emoji: '🔒',
    type: 'security',
    code: ':lock:',
    description: 'Fixing security issues.',
    release: MINOR,
  },
  {
    emoji: '🍎',
    type: 'osx',
    code: ':apple:',
    description: 'Fixing something on macOS.',
    release: PATCH,
  },
  {
    emoji: '🐧',
    type: 'linux',
    code: ':penguin:',
    description: 'Fixing something on Linux.',
    release: PATCH,
  },
  {
    emoji: '🏁',
    type: 'windows',
    code: ':checkered_flag:',
    description: 'Fixing something on Windows.',
    release: PATCH,
  },
  {
    emoji: '🤖',
    type: 'android',
    code: ':robot:',
    description: 'Fixing something on Android.',
    release: PATCH,
  },
  {
    emoji: '🍏',
    type: 'ios',
    code: ':green_apple:',
    description: 'Fixing something on iOS.',
    release: PATCH,
  },
  {
    emoji: '🔖',
    type: 'release',
    code: ':bookmark:',
    description: 'Releasing / Version tags.',
    release: PATCH,
  },
  {
    emoji: '🚨',
    type: 'lint',
    code: ':rotating_light:',
    description: 'Removing linter warnings.',
    release: PATCH,
  },
  {
    emoji: '🚧',
    type: 'wip',
    code: ':construction:',
    description: 'Work in progress.',
    release: false, // don't create a release
  },
  {
    emoji: '💚',
    type: 'fix-ci',
    code: ':green_heart:',
    description: 'Fixing CI Build.',
    release: PATCH,
  },
  {
    emoji: '⬇️',
    type: 'downgrade',
    code: ':arrow_down:',
    description: ' Downgrading dependencies.',
    release: PATCH,
  },
  {
    emoji: '⬆️',
    type: 'upgrade',
    code: ':arrow_up:',
    description: ' Upgrading dependencies.',
    release: PATCH,
  },
  {
    emoji: '📌',
    type: 'pushpin',
    code: ':pushpin:',
    description: 'Pinning dependencies to specific versions.',
    release: false,
  },
  {
    emoji: '👷',
    type: 'ci',
    code: ':construction_worker:',
    description: 'Adding CI build system.',
    release: PATCH,
  },
  {
    emoji: '📈',
    type: 'analytics',
    code: ':chart_with_upwards_trend:',
    description: 'Adding analytics or tracking code.',
    release: PATCH,
  },
  {
    emoji: '♻️',
    type: 'refactoring',
    code: ':recycle:',
    description: ' Refactoring code.',
    release: MINOR,
  },
  {
    emoji: '🐳',
    type: 'docker',
    code: ':whale:',
    description: 'Work about Docker.',
    release: PATCH,
  },
  {
    emoji: '➕',
    type: 'dep-add',
    code: ':heavy_plus_sign:',
    description: 'Adding a dependency.',
    release: PATCH,
  },
  {
    emoji: '➖',
    type: 'dep-rm',
    code: ':heavy_minus_sign:',
    description: 'Removing a dependency.',
    release: PATCH,
  },
  {
    emoji: '🔧',
    type: 'config',
    code: ':wrench:',
    description: 'Changing configuration files.',
    release: PATCH,
  },
  {
    emoji: '🌐',
    type: 'i18n',
    code: ':globe_with_meridians:',
    description: 'Internationalization and localization.',
    release: PATCH,
  },
  {
    emoji: '✏️',
    type: 'typo',
    code: ':pencil2:',
    description: ' Fixing typos.',
    release: PATCH,
  },
  {
    emoji: '💩',
    type: 'poo',
    code: ':poop:',
    description: 'Writing bad code that needs to be improved.',
    release: PATCH,
  },
  {
    emoji: '⏪',
    type: 'revert',
    code: ':rewind:',
    description: 'Reverting changes.',
    release: PATCH,
  },
  {
    emoji: '🔀',
    type: 'merge',
    code: ':twisted_rightwards_arrows:',
    description: 'Merging branches.',
    release: PATCH,
  },
  {
    emoji: '📦',
    type: 'dep-up',
    code: ':package:',
    description: 'Updating compiled files or packages.',
    release: PATCH,
  },
  {
    emoji: '👽',
    type: 'compat',
    code: ':alien:',
    description: 'Updating code due to external API changes.',
    release: PATCH,
  },
  {
    emoji: '🚚',
    type: 'mv',
    code: ':truck:',
    description: 'Moving or renaming files.',
    release: PATCH,
  },
  {
    emoji: '📄',
    type: 'license',
    code: ':page_facing_up:',
    description: 'Adding or updating license.',
    release: false,
  },
  {
    emoji: '💥',
    type: 'breaking',
    code: ':boom:',
    description: 'Introducing breaking changes.',
    release: MAJOR,
  },
  {
    emoji: '🍱',
    type: 'assets',
    code: ':bento:',
    description: 'Adding or updating assets.',
    release: PATCH,
  },
  {
    emoji: '👌',
    type: 'review',
    code: ':ok_hand:',
    description: 'Updating code due to code review changes.',
    release: PATCH,
  },
  {
    emoji: '♿️',
    type: 'access',
    code: ':wheelchair:',
    description: 'Improving accessibility.',
    release: PATCH,
  },
  {
    emoji: '💡',
    type: 'docs-code',
    code: ':bulb:',
    description: 'Documenting source code.',
    release: PATCH,
  },
  {
    emoji: '🍻',
    type: 'beer',
    code: ':beers:',
    description: 'Writing code drunkenly.',
    release: PATCH,
  },
  {
    emoji: '💬',
    type: 'texts',
    code: ':speech_balloon:',
    description: 'Updating text and literals.',
    release: PATCH,
  },
  {
    emoji: '🗃',
    type: 'db',
    code: ':card_file_box:',
    description: ' Performing database related changes.',
    release: PATCH,
  },
  {
    emoji: '🔊',
    type: 'log-add',
    code: ':loud_sound:',
    description: 'Adding logs.',
    release: false,
  },
  {
    emoji: '🔇',
    type: 'log-rm',
    code: ':mute:',
    description: 'Removing logs.',
    release: false,
  },
  {
    emoji: '👥',
    type: 'contrib-add',
    code: ':busts_in_silhouette:',
    description: 'Adding contributor(s).',
    release: false,
  },
  {
    emoji: '🚸',
    type: 'ux',
    code: ':children_crossing:',
    description: 'Improving user experience / usability.',
    release: PATCH,
  },
  {
    emoji: '🏗',
    type: 'arch',
    code: ':building_construction:',
    description: ' Making architectural changes.',
    release: PATCH,
  },
  {
    emoji: '📱',
    type: 'iphone',
    code: ':iphone:',
    description: 'Working on responsive design.',
    release: PATCH,
  },
  {
    emoji: '🤡',
    type: 'clown-face',
    code: ':clown_face:',
    description: 'Mocking things.',
    release: false,
  },
  {
    emoji: '🥚',
    type: 'egg',
    code: ':egg:',
    description: 'Adding an easter egg.',
    release: PATCH,
  },
  {
    emoji: '🙈',
    type: 'see-no-evil',
    code: ':see_no_evil:',
    description: 'Adding or updating a .gitignore file',
    release: false,
  },
  {
    emoji: '📸',
    type: 'camera-flash',
    code: ':camera_flash:',
    description: 'Adding or updating snapshots',
    release: false,
  },
  {
    emoji: '⚗',
    type: 'experiment',
    code: ':alembic:',
    description: ' Experimenting new things',
    release: false,
  },
  {
    emoji: '🔍',
    type: 'seo',
    code: ':mag:',
    description: 'Improving SEO',
    release: PATCH,
  },
  {
    emoji: '☸️',
    type: 'k8s',
    code: ':wheel_of_dharma:',
    description: ' Work about Kubernetes',
    release: PATCH,
  },
  {
    emoji: '🏷️',
    type: 'types',
    code: ':label:',
    description: ' Adding or updating types (Flow, TypeScript)',
    release: PATCH,
  },
  {
    emoji: '🌱',
    type: 'seed',
    code: ':seedling:',
    description: 'Adding or updating seed files',
    release: PATCH,
  },
  {
    emoji: '🚩',
    type: 'flags',
    code: ':triangular_flag_on_post:',
    description: 'Adding, updating, or removing feature flags',
    release: PATCH,
  },
  {
    emoji: '💫',
    type: 'animation',
    code: ':dizzy:',
    description: 'Adding or updating animations and transitions',
    release: PATCH,
  },
];
