module.exports = [
  {
    emoji: '🎨',
    code: ':art:',
    description: 'Improving structure / format of the code.',
    type: 'style',
  },
  {
    emoji: '⚡️',
    code: ':zap:',
    description: 'Improving performance.',
    type: 'perf',
  },
  {
    emoji: '🔥',
    code: ':fire:',
    description: 'Removing code or files.',
    type: 'prune',
  },
  {
    emoji: '🐛',
    code: ':bug:',
    description: 'Fixing a bug.',
    type: 'fix',
  },
  {
    emoji: '🚑',
    code: ':ambulance:',
    description: 'Critical hotfix.',
    type: 'quickfix',
  },
  {
    emoji: '✨',
    code: ':sparkles:',
    description: 'Introducing new features.',
    type: 'feature',
  },
  {
    emoji: '📝',
    code: ':pencil:',
    description: 'Writing docs.',
    type: 'docs',
  },
  {
    emoji: '🚀',
    code: ':rocket:',
    description: 'Deploying stuff.',
    type: 'deploy',
  },
  {
    emoji: '💄',
    code: ':lipstick:',
    description: 'Updating the UI and style files.',
    type: 'ui',
  },
  {
    emoji: '🎉',
    code: ':tada:',
    description: 'Initial commit.',
    type: 'init',
  },
  {
    emoji: '✅',
    code: ':white_check_mark:',
    description: 'Adding tests.',
    type: 'test',
  },
  {
    emoji: '🔒',
    code: ':lock:',
    description: 'Fixing security issues.',
    type: 'security',
  },
  {
    emoji: '🍎',
    code: ':apple:',
    description: 'Fixing something on macOS.',
    type: 'osx',
  },
  {
    emoji: '🐧',
    code: ':penguin:',
    description: 'Fixing something on Linux.',
    type: 'linux',
  },
  {
    emoji: '🏁',
    code: ':checkered_flag:',
    description: 'Fixing something on Windows.',
    type: 'windows',
  },
  {
    emoji: '🤖',
    code: ':robot:',
    description: 'Fixing something on Android.',
    type: 'android',
  },
  {
    emoji: '🍏',
    code: ':green_apple:',
    description: 'Fixing something on iOS.',
    type: 'ios',
  },
  {
    emoji: '🔖',
    code: ':bookmark:',
    description: 'Releasing / Version tags.',
    type: 'release',
  },
  {
    emoji: '🚨',
    code: ':rotating_light:',
    description: 'Removing linter warnings.',
    type: 'lint',
  },
  {
    emoji: '🚧',
    code: ':construction:',
    description: 'Work in progress.',
    type: 'wip',
  },
  {
    emoji: '💚',
    code: ':green_heart:',
    description: 'Fixing CI Build.',
    type: 'fix-ci',
  },
  {
    emoji: '⬇️',
    code: ':arrow_down:',
    description: ' Downgrading dependencies.',
    type: 'downgrade',
  },
  {
    emoji: '⬆️',
    code: ':arrow_up:',
    description: ' Upgrading dependencies.',
    type: 'upgrade',
  },
  {
    emoji: '📌',
    code: ':pushpin:',
    description: 'Pinning dependencies to specific versions.',
    type: 'pushpin',
  },
  {
    emoji: '👷',
    code: ':construction_worker:',
    description: 'Adding CI build system.',
    type: 'ci',
  },
  {
    emoji: '📈',
    code: ':chart_with_upwards_trend:',
    description: 'Adding analytics or tracking code.',
    type: 'analytics',
  },
  {
    emoji: '♻️',
    code: ':recycle:',
    description: ' Refactoring code.',
    type: 'refactoring',
  },
  {
    emoji: '🐳',
    code: ':whale:',
    description: 'Work about Docker.',
    type: 'docker',
  },
  {
    emoji: '➕',
    code: ':heavy_plus_sign:',
    description: 'Adding a dependency.',
    type: 'dep-add',
  },
  {
    emoji: '➖',
    code: ':heavy_minus_sign:',
    description: 'Removing a dependency.',
    type: 'dep-rm',
  },
  {
    emoji: '🔧',
    code: ':wrench:',
    description: 'Changing configuration files.',
    type: 'config',
  },
  {
    emoji: '🌐',
    code: ':globe_with_meridians:',
    description: 'Internationalization and localization.',
    type: 'i18n',
  },
  {
    emoji: '✏️',
    code: ':pencil2:',
    description: ' Fixing typos.',
    type: 'typo',
  },
  {
    emoji: '💩',
    code: ':poop:',
    description: 'Writing bad code that needs to be improved.',
    type: 'poo',
  },
  {
    emoji: '⏪',
    code: ':rewind:',
    description: 'Reverting changes.',
    type: 'revert',
  },
  {
    emoji: '🔀',
    code: ':twisted_rightwards_arrows:',
    description: 'Merging branches.',
    type: 'merge',
  },
  {
    emoji: '📦',
    code: ':package:',
    description: 'Updating compiled files or packages.',
    type: 'dep-up',
  },
  {
    emoji: '👽',
    code: ':alien:',
    description: 'Updating code due to external API changes.',
    type: 'compat',
  },
  {
    emoji: '🚚',
    code: ':truck:',
    description: 'Moving or renaming files.',
    type: 'mv',
  },
  {
    emoji: '📄',
    code: ':page_facing_up:',
    description: 'Adding or updating license.',
    type: 'license',
  },
  {
    emoji: '💥',
    code: ':boom:',
    description: 'Introducing breaking changes.',
    type: 'breaking',
  },
  {
    emoji: '🍱',
    code: ':bento:',
    description: 'Adding or updating assets.',
    type: 'assets',
  },
  {
    emoji: '👌',
    code: ':ok_hand:',
    description: 'Updating code due to code review changes.',
    type: 'review',
  },
  {
    emoji: '♿️',
    code: ':wheelchair:',
    description: 'Improving accessibility.',
    type: 'access',
  },
  {
    emoji: '💡',
    code: ':bulb:',
    description: 'Documenting source code.',
    type: 'docs-code',
  },
  {
    emoji: '🍻',
    code: ':beers:',
    description: 'Writing code drunkenly.',
    type: 'beer',
  },
  {
    emoji: '💬',
    code: ':speech_balloon:',
    description: 'Updating text and literals.',
    type: 'texts',
  },
  {
    emoji: '🗃',
    code: ':card_file_box:',
    description: ' Performing database related changes.',
    type: 'db',
  },
  {
    emoji: '🔊',
    code: ':loud_sound:',
    description: 'Adding logs.',
    type: 'log-add',
  },
  {
    emoji: '🔇',
    code: ':mute:',
    description: 'Removing logs.',
    type: 'log-rm',
  },
  {
    emoji: '👥',
    code: ':busts_in_silhouette:',
    description: 'Adding contributor(s).',
    type: 'contrib-add',
  },
  {
    emoji: '🚸',
    code: ':children_crossing:',
    description: 'Improving user experience / usability.',
    type: 'ux',
  },
  {
    emoji: '🏗',
    code: ':building_construction:',
    description: ' Making architectural changes.',
    type: 'arch',
  },
  {
    emoji: '📱',
    code: ':iphone:',
    description: 'Working on responsive design.',
    type: 'iphone',
  },
  {
    emoji: '🤡',
    code: ':clown_face:',
    description: 'Mocking things.',
    type: 'clown-face',
  },
  {
    emoji: '🥚',
    code: ':egg:',
    description: 'Adding an easter egg.',
    type: 'egg',
  },
  {
    emoji: '🙈',
    code: ':see_no_evil:',
    description: 'Adding or updating a .gitignore file',
    type: 'see-no-evil',
  },
  {
    emoji: '📸',
    code: ':camera_flash:',
    description: 'Adding or updating snapshots',
    type: 'camera-flash',
  },
  {
    emoji: '⚗',
    code: ':alembic:',
    description: ' Experimenting new things',
    type: 'experiment',
  },
  {
    emoji: '🔍',
    code: ':mag:',
    description: 'Improving SEO',
    type: 'seo',
  },
  {
    emoji: '☸️',
    code: ':wheel_of_dharma:',
    description: ' Work about Kubernetes',
    type: 'k8s',
  },
  {
    emoji: '🏷️',
    code: ':label:',
    description: ' Adding or updating types (Flow, TypeScript)',
    type: 'types',
  },
  {
    emoji: '🌱',
    code: ':seedling:',
    description: 'Adding or updating seed files',
    type: 'seed',
  },
  {
    emoji: '🚩',
    code: ':triangular_flag_on_post:',
    description: 'Adding, updating, or removing feature flags',
    type: 'flags',
  },
  {
    emoji: '💫',
    code: ':dizzy:',
    description: 'Adding or updating animations and transitions',
    type: 'animation',
  },
];
